services:
  - type: web
    name: iris
    runtime: python
    buildCommand: pip install -r requirements_imagekit.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 --threads 2 --timeout 120 app_imagekit:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
