services:
  - type: web
    name: iris
    runtime: python
    buildCommand: pip install -r requirements_imagekit.txt
    startCommand: gunicorn app_imagekit:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
